name: Show Pull Request Event

on:
  pull_request:
    branches:
      - master

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: echo ${{ toJson(github.event) }}
